admin_gestion:
    resource: "@AdminBundle/Resources/config/routing/admin.yml"
    prefix:   /admin/gestion

admin_dashboard:
    resource: "@AdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /admin
