imports:
    - { resource: config_dev.yml }
    - { resource: parameters_debug.yml }

parameters:
    database_host: '%database_host_debug%'
    database_port: '%database_port_debug%'
    database_name: '%database_name_debug%'
    database_user: '%database_user_debug%'
    database_password: '%database_password_debug%'

media:
    use_external_domain: true
    domain: "%definima_media_domain%"

twig:
    globals:
        external_domain: "%definima_media_domain%"