imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    templating:
        engines: ['twig']
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        agenceCrea: Definima
        nom_site: Socle Symfony
        societe: Definima
        siteWeb: socle@definima.com
        mail: valentin@definima.net

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        types:
            media: MediaBundle\Type\MediaType
            media_collection: MediaBundle\Type\MediaCollectionType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                DATE_FORMAT: AppBundle\DQL\DateFormatFunction
                DATE: AppBundle\DQL\Date
                TIME: AppBundle\DQL\Time
            string_functions:
                GROUP_CONCAT: AppBundle\DQL\GroupConcat


cmf_seo:
    persistence:
        orm: true
    content_listener:
        enabled: false
    sitemap:
        enabled: false
    form:
        data_class:
            seo_metadata: 'Symfony\Cmf\Bundle\SeoBundle\Model\SeoMetadata'
        options:
            generic_metadata: true


sonata_seo:
    encoding:         UTF-8
    page:
        title:            Vos professionnels proches de chez vous - Rcommerce
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             "Rcommerce"
                description:          "Retrouvez avec RCommerce vos professionnels proches de chez vous (Belin-Beliet ou Bassin d'arcachon). Nos artisans vous accompagnent dans votre quotidien."

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       "Rcommerce"
                'og:description':     "Retrouvez avec RCommerce vos professionnels proches de chez vous (Belin-Beliet ou Bassin d'arcachon). Nos artisans vous accompagnent dans votre quotidien."

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
#    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    service:
        user_manager: pugx_user_manager
        mailer: fos_user.mailer.twig_swift


pugx_multi_user:
    users:
        admin:
            entity:
                class: AdminBundle\Entity\Admin
#        Bon exemple de réécriture de PUGX

#        candidat:
#            entity:
#                class: CandidatBundle\Entity\Candidat
#            registration:
#                form:
#                    type: CandidatBundle\Form\CandidatRegisterType
#                    name: fos_user_registration_form
#                    validation_groups:  [Registration, Default]
#                template: DefinimaCandidatBundle:Candidat:register.html.twig


stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sortable: true
            loggable: true
            sluggable: true

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            compass: false
            public: true

media:
    conf:
        admin_profil:
            dir: "../web/uploads/public/admin/profil"
            type: 'file'
            accept: '.jpeg,.jpg,.png'
            upload:
                max_file_size: 2097152 #10Mo (1Mo = 1048576) size in bytes
                image_versions: {'thumbnail': {crop: true, max_width: 600, max_height: 600}, 'slider': {crop: true, max_width: 870, max_height: 630}}
