admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sitemaps:
    prefix: /sitemaps
    resource: "@CmfSeoBundle/Resources/config/routing/sitemap.xml"