# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        admin:
            entity: { class: AdminBundle:Admin, property: username }
        admin_provider:
            chain:
                providers: [admin]

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            switch_user: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            access_denied_handler: AppBundle\Security\AccessDeniedHandler

        admin:
            pattern: ^/admin
            switch_user: true
            form_login:
                provider: admin_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: admin_login_check
                login_path: admin_login
                default_target_path: admin_dashboard_index
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                secret: 'tokenrememberme33'
                lifetime: 604800 # 1 week in seconds
                path: admin_login
            logout_on_user_change: true
            access_denied_handler: AdminBundle\Security\AccessDeniedHandler

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }