<?php

namespace AdminBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {

        return $this->createQueryBuilder('a')
            ->where('a.isDeleted = 0')
            ->getQuery()
            ->getResult();


    }
}
