app_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_ville_ajax:
    path:     /villeajax
    defaults: { _controller: AppBundle:Default:villeAjax }
    methods:  [GET, POST]
