admin_gestion_admin_index:
    path:     /
    defaults: { _controller: "AdminBundle:Admin:index" }
    methods:  GET
    
admin_gestion_admin_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Admin:new" }
    methods:  [GET, POST]

admin_gestion_admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Admin:edit" }
    methods:  [GET, POST]

admin_gestion_admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Admin:delete" }
    methods:  DELETE

admin_gestion_admin_console:
    path:     /console
    defaults: { _controller: "AdminBundle:Admin:console" }
    methods:  GET
    
admin_gestion_admin_commande:
    path:     /{commande}/cmd
    defaults: { _controller: "AdminBundle:Admin:commande" }
    methods:  GET
